# https://argo-cd.readthedocs.io/en/stable/getting_started/
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/
---
- name: Install Argo CD on RKE cluster
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
    - vars/argocd.yml
  vars:
    kubeconfig: "{{ rke_kubeconfig }}"
  tasks:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
    - name: Create Argo CD ingress secret
      vars:
        cert_desc: Argo CD
        cert_file: argocd
        secret_name: argocd-server-tls
        secret_ns: "{{ argocd_namespace }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.yml

    # https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
    - name: Install Argo CD Helm chart
      vars:
        # required kubernetes>=24.2 package only in user virtualenv
        ansible_python_interpreter: "{{ venv_python_interpreter }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        chart_repo_url: https://argoproj.github.io/argo-helm
        chart_ref: argo-cd
        chart_version: "{{ argocd_chart_version }}"
        release_name: argocd
        release_namespace: "{{ argocd_namespace }}"
        release_values: "{{ argocd_chart_values }}"
        atomic: true
      timeout: 300

    - name: >-
        {{ 'Enable' if enabled else 'Disable' }}
        Istio service mesh
      vars:
        enabled: "{{ argocd_use_mesh }}"
        apps_ns: "{{ argocd_namespace }}"
        services:
          - argocd-server
          - argocd-applicationset-controller
          - argocd-commit-server
          - argocd-repo-server
        resources: |
          {% set res = [] %}
          {% for svc in services %}
          {%  set _ = res.append({
                'kind':'Service',
                'name': svc
              }) %}
          {% endfor %}
          {{ res }}
      ansible.builtin.include_tasks: tasks/istio/mesh.yml
  any_errors_fatal: true
