---
- name: Show remote and local facts
  tags: facts
  hosts: control_plane
  gather_facts: true
  pre_tasks:
    - name: Get controller facts
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/localfacts.yml
      when: local_python_interpreter is not defined
  tasks:
    - name: Dump "ansible_facts"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
      ansible.builtin.debug:
        var: ansible_facts

    - name: Dump "ansible_local"
      ansible.builtin.debug:
        var: ansible_local

    - name: Local Python interpreter
      ansible.builtin.debug:
        var: local_python_interpreter

    - name: Local timezone offset
      ansible.builtin.debug:
        var: local_tz_offset

- name: Show hosts and domain names
  tags: hosts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show inventory groups
      ansible.builtin.debug:
        msg: |-
          groups['all']:              {{ groups['all'] }}
          groups['k8s_all']:          {{ groups['k8s_all'] }}
          groups['cluster']:          {{ groups['cluster'] }}
          groups['control_plane']:    {{ groups['control_plane'] }}
          groups['control_plane_ha']: {{ groups['control_plane_ha'] }}
          groups['workers']:          {{ groups['workers'] }}
          groups['workers_ha']:       {{ groups['workers_ha'] }}

    - name: Generate cluster FQDNs
      vars:
        search_domains: ["fourteeners.local"]
        rke_cluster_name: homelab
        rke_fqdns: >
          {{ ([rke_cluster_name] + groups['control_plane']) |
          product(search_domains) | map('join','.') | list }}
      ansible.builtin.debug:
        msg: |-
          rke_fqdns[0]:  {{ rke_fqdns[0]  }}
          rke_fqdns[1:]: {{ rke_fqdns[1:] }}

    - name: Generate hosts entries
      vars:
        search_domains:
          - fourteeners.local
          - erhhungyuan.com
        rke_cluster_name: homelab
        rke_ha_mode: true
        k8s_hosts: |
          {% set hosts = groups['k8s_all'] %}
          {% if rke_ha_mode %}
          {%   set _ = hosts.append(rke_cluster_name) %}
          {% endif %}
          {{ hosts }}
        host_ip: "{{ hostvars[host]['ansible_host'] }}"
        # if HA mode, the host "homelab" (cluster name) has its own virtual IP
        # if not HA mode, homelab is an alias for the first control plane node
        host_names: |
          {% set use_alias = not rke_ha_mode and host == rke_control_plane_host %}
          {{ [host, rke_cluster_name] if use_alias else [host] }}
        host_fqdns: "{{ host_names | product(search_domains) | map('join', '.')  | list }}"
        host_pairs: "{{ host_fqdns | map('regex_replace', '^([^.]+)', '\\1 \\1') | list }}"
        host_entry: "{{ ([host_ip] + (host_pairs | join(' ')) | split | unique) | join(' ') }}"
      ansible.builtin.debug:
        msg: "{{ host_entry }}"
      loop: "{{ k8s_hosts }}"
      loop_control:
        loop_var: host
        label: "{{ host_ip }}|{{ host }}"

- name: Show certificates on CA server
  tags: certs
  hosts: _pki
  gather_facts: false
  tasks:
    - name: Fetch cert file
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command: cat certs/rancher.pem
      register: cat_cert
      changed_when: false

    - name: Print cert file
      ansible.builtin.debug:
        msg: "{{cat_cert.stdout }}"

    - name: Print cert file
      vars:
        # split chain into individual certs:
        # host, intermediate CA, and root CA
        chain: "{{ cat_cert.stdout | regex_findall(
          '(-----BEGIN CERTIFICATE-----(?:\\n\\S+)+\\n-----END CERTIFICATE-----)',
          multiline=True) }}"
        certs:
          # tls.crt: host and intermediate CA certs
          tls.crt: "{{ chain[:-1] | join('\n') }}"
          ca.crt: "{{  chain[-1:] | join('\n') }}"
      ansible.builtin.debug:
        var: certs

- name: Dump Helm chart values files
  tags: values
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
    - vars/harbor.yml
    - vars/argocd.yml
  tasks:
    - name: Write Helm chart values file
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        set -o pipefail
        jq <<'EOF' | yq -pj -oy > /tmp/{{ item.dest }}
        {{ item.json }}
        EOF
      args:
        executable: /bin/bash
      loop:
        - json: "{{ harbor_chart_values | to_json }}"
          dest: values-harbor.yaml
        - json: "{{ argocd_chart_values | to_json }}"
          dest: values-argocd.yaml
      loop_control:
        label: "{{ item.dest }}"
      changed_when: true

- name: Debug basic Ansible/Jinja syntax
  tags: syntax
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create IP address range
      vars:
        rke_lb_vip: 192.168.0.221
        valkey_cluster_nodes: 6
        valkey_lb_ips: |
          {% set ips = [] %}
          {% for i in range(valkey_cluster_nodes) %}
          {%   set _ = ips.append(rke_lb_vip | ansible.utils.ipmath(i+1)) %}
          {% endfor %}
          {{ ips }}
      ansible.builtin.debug:
        var: valkey_lb_ips

    - name: Flatten nested lists
      vars:
        add_list:
          - id: 1
            names: ["foo", "bar"]
          - id: 2
            names: ["bar", "baz"]
        the_list: |
          {% set items = [] %}
          {% set _ = items.append(add_list) %}
          {# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/flatten_filter.html #}
          {{ items | ansible.builtin.flatten }}
      ansible.builtin.debug:
        var: the_list

- name: Debug expressions and statements
  tags: exprs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug filtering functions
      vars:
        vc_pods:
          - ^kube-system/coredns-.*$
        get_pods: # kubernetes.core.k8s_info
          resources:
            - metadata:
                name: coredns-668c87c5d8-mjp84
                namespace: kube-system
            - metadata:
                name: argocd-application-controller-0
                namespace: argocd
        user_pods: |
          {% set pods = [] %}
          {% for meta in get_pods.resources | map(attribute='metadata') %}
          {%   set desc = meta.namespace ~'/'~ meta.name %}
          {#   use namespace() to create a scoped object #}
          {#   https://jinja.palletsprojects.com/en/stable/templates/#assignments #}
          {%   set pod = namespace(desc=desc, found=false) %}
          {%   for regex in vc_pods %}
          {%     if not pod.found and pod.desc | regex_search(regex) %}
          {%        set pod.found = true %}
          {%     endif %}
          {%   endfor  %}
          {%   if not pod.found %}
          {%     set _ = pods.append({
                   'name':      meta.name,
                   'namespace': meta.namespace
                 })  %}
          {%   endif %}
          {% endfor  %}
          {{ pods    }}
      ansible.builtin.debug:
        var: user_pods

    - name: Debug regular expressions
      vars:
        find: install
        text: Host purged; no K3s/Rancher; before installing RKE2
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/search_test.html
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/regex_escape_filter.html
        found: "{{ text is search(find | regex_escape, ignorecase=true) }}"
      ansible.builtin.debug:
        msg: |2-
           find: {{ find }}
           text: {{ text }}
          found: {{ found }}

    - name: Debug create query string
      vars:
        query_params:
          ssl: "true"
          sslmode: verify-full
          sslcert: /tmp/tls/tls.crt
          sslkey: /tmp/tls/tls.key
          sslrootcert: /tmp/tls/ca.crt
        query_string: |-
          {% set  items = query_params | dict2items -%}
          {% set params = items | map(attribute='key')    |
                      zip(items | map(attribute='value')) |
                      map('join','=') -%}
          {{ params | join('&') }}
      ansible.builtin.debug:
        var: query_string

- name: Debug various Ansible filters
  tags: filters
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug password_hash filter
      vars:
        credentials:
          user11: password1
          user12: password1
          user21: password2
          user22: password2
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_hash_filter.html
        # (requires Python packages "passlib" and "bcrypt==4.0.1" on Ansible controller)
        # bcrypt_salt is group var (must be exactly 22 characters) defined in common.yml
        username_hash: "{{ item[0] | ansible.builtin.password_hash('bcrypt', salt=bcrypt_salt, rounds=bcrypt_rounds) }}"
        custom_salt: "{{ username_hash[-1 * bcrypt_salt | length :]}}"
        password_hash: "{{ item[1] | ansible.builtin.password_hash('bcrypt', salt=custom_salt, rounds=bcrypt_rounds) }}"
      ansible.builtin.debug:
        var: password_hash
      loop: "{{ credentials.items() }}"
      loop_control:
        label: "{{ item[0] }}"

    - name: Debug dict2items filter
      vars:
        users:
          alice:
            age: 18
            email: alice@example.com
          bob:
            age: 21
            email: bob@example.com
      ansible.builtin.debug:
        var: item
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dict2items_filter.html
      loop: "{{ users | ansible.builtin.dict2items(key_name='user', value_name='info') }}"
      loop_control:
        label: "{{ item.user }}"

    - name: Debug dict_kv filter
      vars:
        dashboards:
          - title: Istio Mesh Dashboard
            gnetId: 7639
          - title: Istio Ztunnel Dashboard
            gnetId: 21306
          - title: Istio Service Dashboard
            gnetId: 7636
          - title: Istio Workload Dashboard
            gnetId: 7630
          - title: Istio Performance Dashboard
            gnetId: 11829
          - title: Istio Control Plane Dashboard
            gnetId: 7645
          - title: Istio Wasm Extension Dashboard
            gnetId: 13277
        # https://docs.ansible.com/ansible/latest/collections/community/general/dict_kv_filter.html
        names: "{{ dashboards | map(attribute='title') | map('community.general.dict_kv', 'name') }}"
      ansible.builtin.debug:
        var: names

    - name: Is truthy expression
      vars:
        expressions:
          - desc: empty string
            expr: ""
          - desc: 1-item list
            expr: ["foo"]
          - desc: empty list
            expr: []
          - desc: 1-key dict
            expr: {foo: bar}
          - desc: empty dict
            expr: {}
          - desc: number one
            expr: 1
          - desc: number zero
            expr: 0
      ansible.builtin.debug:
        msg: "{{ item.desc }}: {{ item.expr is truthy }}"
      loop: "{{ expressions }}"
      loop_control:
        label: "{{ item.desc }}"

- name: Useful collection of tasks
  tags: tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Exit the play successfully
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/meta_module.html
      ansible.builtin.meta: end_play
