---
- name: Include package installs playbook
  ansible.builtin.import_playbook: packages.yml

- name: Include system settings playbook
  ansible.builtin.import_playbook: basics.yml

- name: Include home directory setup playbook
  ansible.builtin.import_playbook: files.yml

- name: Include Rancher K3s cluster playbook
  ansible.builtin.import_playbook: rancher.yml

- name: Include Rancher RKE cluster playbook
  ansible.builtin.import_playbook: cluster.yml

- name: Include storage provisioners playbook
  ansible.builtin.import_playbook: storage.yml

- name: Include resource manifests playbook
  ansible.builtin.import_playbook: manifests.yml

- name: Include Harbor OCI registry playbook
  ansible.builtin.import_playbook: harbor.yml

- name: Include OpenSearch cluster playbook
  ansible.builtin.import_playbook: opensearch.yml

- name: Include Fluent Bit logging playbook
  ansible.builtin.import_playbook: logging.yml

- name: Include PostgreSQL database playbook
  ansible.builtin.import_playbook: postgresql.yml

- name: Include Keycloak IAM & OIDC playbook
  ansible.builtin.import_playbook: keycloak.yml

- name: Include Istio service mesh playbook
  ansible.builtin.import_playbook: istio.yml

- name: Include Argo CD GitOps tool playbook
  ansible.builtin.import_playbook: argocd.yml

- name: Include virtual clusters playbook
  ansible.builtin.import_playbook: vclusters.yml
