---
- name: Include package installs playbook
  ansible.builtin.import_playbook: packages.yml

- name: Include system settings playbook
  ansible.builtin.import_playbook: basics.yml

- name: Include home directory setup playbook
  ansible.builtin.import_playbook: files.yml

- name: Include Rancher K3s cluster playbook
  ansible.builtin.import_playbook: rancher.yml

- name: Include Rancher RKE cluster playbook
  ansible.builtin.import_playbook: cluster.yml

- name: Include storage provisioners playbook
  ansible.builtin.import_playbook: storage.yml

- name: Include resource manifests playbook
  ansible.builtin.import_playbook: manifests.yml

- name: Include Harbor OCI registry playbook
  ansible.builtin.import_playbook: harbor.yml

- name: Include Argo CD GitOps tool playbook
  ansible.builtin.import_playbook: argocd.yml

- name: Include virtual clusters playbook
  ansible.builtin.import_playbook: vclusters.yml
