# applies all Kubernetes manifests in the "manifests" directory
# IMPORTANT: manifests must specify namespaces to install into
---
- name: Create resources on {{ rke_cluster_name }} cluster
  hosts: controlplane
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
  tasks:
    - name: Apply Kubernetes manifests
      vars:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fileglob_lookup.html
        manifests: "{{ lookup('ansible.builtin.fileglob', 'manifests/*.y*ml', wantlist=True) }}"
        # required kubernetes>=24.2 package only in user virtualenv
        ansible_python_interpreter: "{{ venv_python_interpreter }}"
      run_once: true
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
      kubernetes.core.k8s:
        kubeconfig: "{{ rke_kubeconfig }}"
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html
        definition: "{{ lookup('ansible.builtin.file', item) }}"
        state: present
        apply: true
        wait: true
      loop: "{{ manifests }}"
      loop_control:
        label: "{{ item | basename }}"
      timeout: 60
  any_errors_fatal: true
