# https://prometheus-operator.dev/
# https://github.com/prometheus-operator/kube-prometheus
# https://runbooks.prometheus-operator.dev/runbooks
---
- name: Install Prometheus monitoring stack
  tags: stack
  hosts: "{{ rke_control_plane_host }}"
  gather_facts: false
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
    - vars/storage.yml
    - vars/minio.yml
    - vars/monitoring.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ monitoring_namespace }}"
    create_ns: false
  pre_tasks:
    # determine whether to create the node exporter
    # RBAC config before installing the Helm chart
    - name: Is Helm chart already installed?
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_info_module.html
      kubernetes.core.helm_info:
        kubeconfig: "{{ kubeconfig }}"
        release_name: "{{ monitoring_release_name }}"
        release_namespace: "{{ monitoring_namespace }}"
        release_state:
          - deployed
      register: helm_info
  tasks:
    # client certs for etcd ServiceMonitor
    # (turns out not needed as the metrics
    # endpoint is only available via HTTP)
    - name: Create RKE etcd client secret
      vars:
        cert_desc: RKE etcd client
        cert_file: etcd/client
        secret_name: "{{ monitoring_secrets['etcd'] }}"
        create_ns: true
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.rke.yml

    - name: Create monitoring ingress secret
      vars:
        cert_desc: "{{ item.desc }} ingress"
        cert_file: "{{ item.file }}"
        secret_name: "{{ item.name }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.pki.yml
      loop:
        - name: "{{ monitoring_secrets['prometheus'] }}"
          desc: Prometheus
          file: prometheus
        - name: "{{ monitoring_secrets['thanos'] }}"
          desc: Thanos
          file: thanos
        - name: "{{ monitoring_secrets['alertmanager'] }}"
          desc: Alertmanager
          file: alertmanager
        - name: "{{ monitoring_secrets['grafana'] }}"
          desc: Grafana
          file: grafana
      loop_control:
        label: "{{ item.file }}"

    - name: Create monitoring scraper secret
      vars:
        cert_desc: scraping client
        cert_file: scraper
        secret_name: "{{ monitoring_secrets['scraper'] }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.pki.yml
      # sets pem_chain fact

    # CA certs to be stored inline with Grafana data
    # source configs for Prometheus and Alertmanager
    - name: Set ca_certs fact from pem_chain
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        # pem_chain fact set by tasks/k8s/secrets/tls.pki.yml
        # above contains both intermediate and root CA certs
        ca_certs: "{{ pem_chain[1:] | join('\n') }}"

    - name: Create monitoring credentials secret
      vars:
        grafana: "{{ prometheus_stack_chart_values.grafana }}"
        secret_name: "{{ monitoring_secrets['credentials'] }}"
        secret_data: |
          {{ {
               grafana.admin.userKey:            'admin',
               grafana.admin.passwordKey: grafana_admin_pass
          } }}
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml

    # this step is necessary before the Helm release has ever been
    # installed because the Helm-generated template will have both
    # the original prometheus-node-exporter-rbac-config ConfigMap
    # as well as the modified version from extraManifests section
    # of the chart values, which causes duplicate resource error
    # unless an existing "Helm-managed" resource can be imported
    - name: Create node exporter RBAC config
      vars:
        manifest: "{{ prometheus_stack_chart_values.extraManifests[0] }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ manifest.metadata.name }}"
            namespace: "{{ monitoring_namespace }}"
            labels:
              app.kubernetes.io/managed-by: Helm
            annotations:
              meta.helm.sh/release-name: "{{ monitoring_release_name }}"
              meta.helm.sh/release-namespace: "{{ monitoring_namespace }}"
          data: "{{ manifest.data }}"
        validate:
          fail_on_error: true
        state: present
        apply: true
      when: helm_info.status is not defined

    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
    - name: Install Prometheus stack Helm chart
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: kube-prometheus-stack
        chart_version: "{{ prometheus_stack_chart_version }}"
        release_name: "{{ monitoring_release_name }}"
        release_namespace: "{{ monitoring_namespace }}"
        release_values: "{{ prometheus_stack_chart_values }}"
        atomic: true
      timeout: 600
