# https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
---
- name: Install PostgreSQL on RKE cluster
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
    - vars/storage.yml
    - vars/postgresql.yml
    - vars/keycloak.yml
  vars:
    kubeconfig: "{{ rke_kubeconfig }}"
  tasks:
    - name: Create PostgreSQL TLS secret
      vars:
        cert_desc: PostgreSQL
        cert_file: postgresql
        secret_name: postgresql-tls
        secret_ns: "{{ postgresql_namespace }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/tlssecret.yml

    # https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx
    - name: Install PostgreSQL HA Helm chart
      vars:
        # required kubernetes>=24.2 package only in user virtualenv
        ansible_python_interpreter: "{{ venv_python_interpreter }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        chart_repo_url: https://charts.bitnami.com/bitnami
        chart_ref: postgresql-ha
        chart_version: "{{ postgresql_chart_version }}"
        release_name: postgresql
        release_namespace: "{{ postgresql_namespace }}"
        release_values: "{{ postgresql_chart_values }}"
        atomic: true
        wait: true
      timeout: 300
  any_errors_fatal: true
