---
# https://docs.k3s.io/installation/configuration
- name: Install single-node K3s cluster
  hosts: rancher
  become: true
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
    - vars/rancher.k3s.yml
  pre_tasks:
    - name: Show configured server options
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
      ansible.builtin.debug:
        # yeah, this prints the K3s token in plain text
        msg: "Server options: {{ k3s_opts | join(' ') }}"
  tasks:
    - name: Install K3s service by script
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        set -o pipefail
        curl -sfL https://get.k3s.io | \
          sh -s - {{ k3s_opts | join(' ') }}
      args:
        executable: /bin/bash
      register: install_k3s
      changed_when: install_k3s.stdout.find('No change detected') == -1

    - name: Wait for k3s service to start
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
      ansible.builtin.systemd_service:
        name: k3s
        state: started

    - name: Create /etc/profile.d/kubectl.sh
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      ansible.builtin.copy:
        dest: /etc/profile.d/kubectl.sh
        content: export KUBECONFIG={{ k3s_kubeconfig }}
        mode: "0644"

    - name: Allow admin user to use crictl
      vars:
        file_path: "{{ item.path }}"
        file_mode: "{{ item.mode }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/mkreadable.yml
      loop:
        - path: "{{ crictl_config }}"
        - path: "{{ containerd_socket }}"
          mode: "0666"

    - name: Merge kubeconfig into local
      vars:
        kubeconfig: "{{ k3s_kubeconfig }}"
        context: "{{ k3s_cluster_name }}"
        server: https://{{ k3s_fqdn }}:6443
      ansible.builtin.include_tasks: tasks/kubeconfig.yml

- name: Install Rancher Server on K3s
  hosts: rancher
  vars_files:
    - vars/basics.yml
    - vars/kubernetes.yml
    - vars/rancher.k3s.yml
  tasks:
    - name: Install cert-manager Helm chart
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_kubeconfig }}"
        chart_repo_url: https://charts.jetstack.io
        chart_ref: cert-manager
        release_name: cert-manager
        release_namespace: cert-manager
        create_namespace: true
        release_values:
          crds:
            enabled: true
        atomic: true
        wait: true
      timeout: 300

    # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster#install-the-rancher-helm-chart
    - name: Install Rancher Server Helm chart
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_kubeconfig }}"
        chart_repo_url: https://releases.rancher.com/server-charts/latest
        chart_ref: rancher
        release_name: rancher
        release_namespace: cattle-system
        create_namespace: true
        release_values:
          replicas: 1
          hostname: "{{ k3s_fqdn }}"
        atomic: true
        wait: true
      timeout: 600

    # https://github.com/rancher/cli
    - name: Install Rancher CLI utility
      become: true
      ansible.builtin.shell: |
        set -o pipefail
        REL="https://github.com/rancher/cli/releases/latest"
        VER=$(curl -Is $REL | sed -En 's/^location:.+\/tag\/v(.+)\r$/\1/p')

        # check if latest version already installed
        BIN=$(command -v rancher) &> /dev/null && {
          ver=$(v=(`rancher --version`); echo ${v[-1]#v})
          [ "$ver" == "$VER" ] && exit 9 # no change
          BIN=$(dirname "$BIN")
        }
        ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm/')
        curl -fsSL "$REL/download/rancher-linux-$ARCH-v${VER}.tar.gz" | \
          tar -xz -C "${BIN:-/usr/local/bin}" --no-same-owner --strip 2 \
          ./rancher-v${VER}/rancher
      args:
        executable: /bin/bash
      register: install_cli
      changed_when: install_cli.rc == 0
      failed_when: >-
        install_cli.rc != 0 and
        install_cli.rc != 9

    - name: Import RKE cluster using API
      ansible.builtin.shell: |
        # restart Bash and load .bash_aliases
        # in order to use my custom functions
        exec /bin/bash <<'EOF'
        set -o pipefail

        TOKEN_DESC="Ansible session"
        ADMIN_PASS="{{ rancher_admin_pass }}"
        . .bash_aliases # loads .rancher_api

        cluster="{{ rke_cluster_name }}"
        id_var="${cluster^^}_ID"
        cluster_id="${!id_var}"

        get_state() {
          rancher_api get clusters/$cluster_id | \
            jq -r '.state // empty'
        }
        if [ ! "$cluster_id" ]; then
          # RKE cluster not imported yet: import it using the Rancher API
          cluster_id=$(rancher_api post clusters @- <<'EOT' | jq -r '.id // empty'
        {
          "import":      true,
          "type":        "cluster",
          "name":        "{{ rke_cluster_name }}",
          "description": "{{ rke_cluster_desc }}"
        }
        EOT
          )
          [ "$cluster_id" ] || {
            echo >&2 "Cluster import failed!"
            exit 1
          }
          echo "Waiting for cluster state to be \"pending\"..."
          until [ "$(get_state)" == pending ]; do sleep 1; done
          export_variables
        fi

        if [ "$(get_state)" != active ]; then
          # output registration manifest URL so it can be applied on control plane node
          reg_url=$(rancher_api get "clusters/$cluster_id/clusterregistrationtokens" | \
            jq --arg baseUrl "$RANCHER_URL" -r '.data[] |
              select(.name == "default-token") |
                if (.manifestUrl // "") != "" then
                  .manifestUrl
                elif (.token // "") != "" then
                  "\($baseUrl)/v3/import/\(.token)_\(.clusterId).yaml"
                else empty
                end
              ')
          [ "$reg_url" ] && echo "REGISTER=$reg_url"
        fi

        # customize cluster appearance in the Rancher UI
        rancher_api put "clusters/$cluster_id" @- <<'EOT' | \
          jq -cM '.annotations | with_entries(select(.key | startswith("ui.rancher")))'
        {
          "name": "{{ rke_cluster_name }}",
          "annotations": {
            "ui.rancher/badge-color":      "{{ ui_badge_color }}",
            "ui.rancher/badge-icon-text":  "{{ ui_badge_icon }}",
            "ui.rancher/badge-text":       "{{ ui_badge_text }}"
          }
        }
        EOT

        # perform CLI login if not already
        config="$HOME/.rancher/cli2.json"
        [ -f $config ] && \
          [ "$(jq -r '.Servers[.CurrentServer].tokenKey // empty' $config)" ] || {

          # request a long-lived token
          token=$(get_token "CLI token")
          id_var="${cluster^^}_DEFAULT_ID"

          rancher login "$RANCHER_URL" \
            --skip-verify      \
            --token   "$token" \
            --context "${!id_var}"
        }
        rancher_logout # delete $LOGIN_TOKEN
        EOF
      timeout: 300
      register: import_rke
      changed_when: true

    - name: Save RKE registration URL
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        # used in cluster.yml
        rke_reg_url: >-
          {% set lines = import_rke.stdout_lines | select('search','^REGISTER=') | list -%}
          {{ lines[0].split('REGISTER=')[1] if lines | length > 0 else '' }}
      when: import_rke.rc == 0

    - name: Show RKE registration URL
      ansible.builtin.debug:
        msg: |-
          rke_reg_url: "{{ rke_reg_url if rke_reg_url is defined else '<undefined>' }}"
