---
- name: Start all or specific VMs
  hosts: "{{ xcp_master }}"
  vars_files:
    - vars/xcp.yml
  vars:
    # targets can be overridden on command-line:
    # ansible-playbook startvms.yml -e targets=rancher
    targets: rancher,cluster
  gather_facts: false
  become: true
  pre_tasks:
    - name: Resolve target hosts
      vars:
        target_hosts: "{{ targets }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/hosts/resolve.yml
  tasks:
    - name: Start resolved VMs
      # cannot use ansible.builtin.shell because XCP-ng 8.2 only has Python 3.6,
      # which requires an older version of Ansible that we don't otherwise need
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html
      ansible.builtin.raw: |
        # run Bash to load .bashrc in order to
        # use exported functions and variables
        exec /bin/bash -l <<'EOT'

        uuid_var="UUID_{{ item | upper }}"
        name_var="NAME_{{ item | upper }}"
        uuid="${!uuid_var}"
        name="${!name_var}"

        case "$(vmstate $uuid)" in
          running)
            echo "VM \"{{ item }}\" is already running"
            ;;
          halted)    startvm  $uuid "$name" ;;
          suspended) resumevm $uuid "$name" ;;
        esac
        EOT
      loop: "{{ resolved_hosts }}"
      changed_when: true
  any_errors_fatal: true
