# https://github.com/rancherfederal/rke2-ansible/blob/main/docs/README.md#defining-your-cluster
---
rke2_cluster:
  children:
    rke2_servers:
      hosts:
        k8s1:
      vars:
        group_rke2_config:
    rke2_agents:
      hosts:
        k8s2:
        k8s3:
        k8s4:
      vars:
        group_rke2_config:
