# pass the following vars:
#   services [optional] list of services
#   commands [optional] list of commands
---
- name: Shut down host "{{ inventory_hostname }}"
  become: true
  block:
    - name: Stop services
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
      loop: "{{ services }}"
      when: >-
        services is defined  and
        services is iterable and
        services | length > 0

    - name: Run commands
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command: "{{ item }}"
      loop: "{{ commands }}"
      when: >-
        commands is defined  and
        commands is iterable and
                    commands | length > 0
      changed_when: commands | length > 0

    - name: Halt system
      # https://docs.ansible.com/ansible/latest/collections/community/general/shutdown_module.html
      community.general.shutdown:
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html
      async: 20
      poll: 0
  any_errors_fatal: true
