# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html
ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/{{
                                  lookup('ansible.builtin.env', 'USER') }}.pem"
ansible_ssh_common_args: -o StrictHostKeyChecking=no -o ForwardAgent=yes
# ansible_become_pass: {vault.yml}

ansible_python_interpreter: /usr/bin/python3
# virtualenv gets created by ansible.builtin.pip in packages.yml
ansible_user_virtualenv: "{{ ansible_facts['user_dir'] }}/.venv"
