---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # must match local_storage_class
  # defined in vars/kubernetes.yml
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
