---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # must match local_storage_class
  # defined in vars/storage.yml
  name: local-storage
  annotations:
    # default StorageClass is created by Longhorn
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
