# Install packages not included in
# Ubuntu 24.04 minimal installation

# see installed packages:
# apt list --installed

install_apt_packages:
  - apt-transport-https
  - locales         # required by community.general.locale_gen
  - bash-completion # required by crictl/kubectl completion
  - less
  - tree
  - htop
  - lsof  # used by custom Bash function "listening"
  - rsync # required by ansible.posix.synchronize
  - emacs-nox
  # iptables is required by Calico networking in RKE2:
  # https://github.com/rancher/rke2/issues/4385#issuecomment-1738848974
  - iptables
  - dnsutils # provides nslookup/dig/host
  - iputils-ping
  - open-iscsi # required by Longhorn storage engine
  - nfs-common # required by Longhorn storage engine
  - python3-pip
  - python3-virtualenv # required by ansible.builtin.pip
  # yq from Apt is not the mikefarah/yq package we want
  - jq
  - jo
  - git  # required by kubernetes.core.helm_plugin
  - helm # requires /etc/apt/sources.list.d/helm.sources

# packages will be installed under
# virtualenv ansible_user_dir/.venv
install_pip_packages:
  - PyYAML
  - jsonpatch
  - kubernetes # required by kubernetes.core.k8s
  - kubernetes-validate

# {name, path, state} all fields optional:
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_plugin_module.html
install_helm_plugins:
  - path: https://github.com/databus23/helm-diff
