# copies specified kubeconfig file on remote host
# to local machine and merge into ~/.kube/config.
# pass the following vars:
#   kubeconfig <required> remote path
#   context    <required> context name
---
- name: Merge kubeconfig into local
  run_once: true
  become: false
  block:
    - name: Set up kubeconfig facts
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        temp_kubeconfig: /tmp/kubeconfig-{{ context }}-temp
        orig_kubeconfig: /tmp/kubeconfig-{{ context }}-orig
        dest_kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"

    - name: Fetch remote kubeconfig
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html
      ansible.builtin.fetch:
        src: "{{ kubeconfig }}"
        dest: "{{ temp_kubeconfig }}"
        flat: true

    - name: Rename kubeconfig items
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command:
        argv:
          - yq
          - (.. | select(. == "default")) = "{{ context }}"
          - -i
          - "{{ temp_kubeconfig }}"
      delegate_to: localhost
      changed_when: true

    - name: Back up local kubeconfig
      ansible.builtin.command:
        argv:
          - cp
          - -f
          - "{{ dest_kubeconfig }}"
          - "{{ orig_kubeconfig }}"
      delegate_to: localhost
      changed_when: true

    - name: Merge kubeconfig files
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        set -o pipefail
        export KUBECONFIG="{{ orig_kubeconfig }}:{{ temp_kubeconfig }}"
        kubectl config view --merge --flatten | \
          sponge "{{ dest_kubeconfig }}"
      args:
        executable: /usr/local/bin/bash
      delegate_to: localhost
      changed_when: true
