---
- name: Get local timezone offset
  # local custom module
  local_timezone_offset:
  delegate_to: localhost
  # prevent sudo prompt
  become: false
  # tz_offset.in_hours and
  # tz_offset.in_seconds
  register: tz_offset
