---
- name: Set up admin user's home directory
  hosts:
    - rancher
    - cluster
  vars_files:
    - vars/files.yml
  tasks:
    - name: Allow sudo commands without password
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
      ansible.builtin.template:
        src: templates/nopasswd.j2
        dest: /etc/sudoers.d/nopasswd
        mode: "0440"
      become: true

    - name: Suppress Apt's script warning message
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/90disable-warning
        content: |
          Apt::Cmd::Disable-Script-Warning true;
        mode: "0644"
      become: true

    - name: Copy dot files into home directory
      ansible.builtin.copy:
        src: "{{ playbook_dir | dirname }}/{{ item }}"
        dest: "{{ ansible_facts['user_dir'] }}/{{ item }}"
        mode: "0644"
        directory_mode: "0755"
      loop: "{{ copy_files }}"
      notify: Touch copied files
  handlers:
    - name: Touch copied files
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        # restart Bash and load copied .bash_aliases
        # in order to use my custom touch functions
        exec /bin/bash -c '
          . .bash_aliases
          # zeros out file time MM:ss
          _touch -t 00 . .sudo_as_admin*
          # now do the same again but recursively
          touchall -t 00 {{ copy_files | map('quote') | join(' ') }}'
      changed_when: true
