# https://docs.rke2.io/install/quickstart
---
- name: RKE2 role
  hosts: cluster
  become: true
  vars_files:
    - vars/lablabs.rke2.yml
  roles:
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#using-roles
    - role: lablabs.rke2

# https://github.com/rancherfederal/rke2-ansible
# - name: RKE2 play
#   hosts: cluster
#   become: true
#   roles:
#     - role: rancherfederal.rke2.rke2
