# pass the following vars:
#   file_path <required> absolute path
#   file_desc [optional] for task name
#   file_mode [optional] default=0644
#    dir_mode [optional] default=0755
---
- name: Ensure {{ desc }} is readable
  vars:
    desc: >-
      {# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/basename_filter.html #}
      {{- file_desc | default('"' ~ (file_path | ansible.builtin.basename) ~ '"') -}}
  become: true
  block:
    - name: Ensure parent dirs readable
      vars:
        dir_names: "{{ file_path.split('/') }}"
        dir_paths: |
          {% set paths = [] %}
          {% for i in range(2, dir_names | length) %}
          {%   set _ = paths.append(dir_names[: i] | join('/')) %}
          {% endfor %}
          {{ paths }}
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
      ansible.builtin.file:
        path: "{{ path }}"
        mode: "{{ dir_mode | default('0755') }}"
      loop: "{{ dir_paths }}"
      loop_control:
        loop_var: path # "item" is already in use by outer loop

    - name: Does {{ desc }} exist?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html
      ansible.builtin.stat:
        path: "{{ file_path }}"
      register: file_check

    - name: Make {{ desc }} readable
      ansible.builtin.file:
        path: "{{ file_path }}"
        mode: "{{ file_mode | default('0644') }}"
      when: file_check.stat.exists
  any_errors_fatal: true
